# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CODING_LAB\PY_QT\test1\test1\startstop.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 181)
        self.auto_2 = QtWidgets.QPushButton(Dialog)
        self.auto_2.setGeometry(QtCore.QRect(350, 60, 211, 101))
        self.auto_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auto_2.setIcon(icon)
        self.auto_2.setIconSize(QtCore.QSize(200, 200))
        self.auto_2.setObjectName("auto_2")
        self.startstop = QtWidgets.QPushButton(Dialog)
        self.startstop.setGeometry(QtCore.QRect(10, 60, 201, 101))
        self.startstop.setText("")
        self.startstop.setIcon(icon)
        self.startstop.setIconSize(QtCore.QSize(200, 200))
        self.startstop.setObjectName("startstop")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(230, 40, 101, 91))
        self.back.setObjectName("back")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.back.setText(_translate("Dialog", "Back"))
        self.label.setText(_translate("Dialog", "Process"))
        self.label_2.setText(_translate("Dialog", "Auto"))
import tankresources_rc
